// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use these files except in compliance with the License. You may obtain
// a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

import "inspectable.idl";
import "Windows.Foundation.idl";
import "Windows.UI.idl";
import "Windows.UI.Xaml.Media.Imaging.idl";

#include "version.h"

#include "..\..\numerics\WinRT\WinRTNumerics.idl"
#include "Canvas.codegen.idl"
#include "WinRTDirectX\WinRTDirectXCommon.idl"
#include "WinRTDirectX\WinRTDirect3D11.idl"
#include "effects\generated\EffectsCommon.abi.idl"
#include "effects\IEffectInput.abi.idl"
#include "effects\IEffect.abi.idl"
#include "effects\Matrix5x4.abi.idl"
#include "CanvasInterfaces.abi.idl"
#include "CanvasDevice.abi.idl"
#include "CanvasBrush.abi.idl"
#include "CanvasBitmap.abi.idl"
#include "CanvasStrokeStyle.abi.idl"
#include "CanvasTextFormat.abi.idl"
#include "CanvasDrawingSession.abi.idl"
#include "CanvasImageSource.abi.idl"
#include "CanvasControl.abi.idl"
#include "CanvasSwapChain.abi.idl"
#include "CanvasSwapChainPanel.abi.idl"

#include "effects\generated\ArithmeticCompositeEffect.abi.idl"
#include "effects\generated\AtlasEffect.abi.idl"
#include "effects\generated\BlendEffect.abi.idl"
#include "effects\generated\BorderEffect.abi.idl"
#include "effects\generated\BrightnessEffect.abi.idl"
#include "effects\generated\ColorMatrixEffect.abi.idl"
#include "effects\generated\ColorSourceEffect.abi.idl"
#include "effects\generated\CompositeEffect.abi.idl"
#include "effects\generated\ConvolveMatrixEffect.abi.idl"
#include "effects\generated\CropEffect.abi.idl"
#include "effects\generated\DirectionalBlurEffect.abi.idl"
#include "effects\generated\DiscreteTransferEffect.abi.idl"
#include "effects\generated\DisplacementMapEffect.abi.idl"
#include "effects\generated\DistantDiffuseEffect.abi.idl"
#include "effects\generated\DistantSpecularEffect.abi.idl"
#include "effects\generated\DpiCompensationEffect.abi.idl"
#include "effects\generated\GammaTransferEffect.abi.idl"
#include "effects\generated\GaussianBlurEffect.abi.idl"
#include "effects\generated\HueRotationEffect.abi.idl"
#include "effects\generated\LinearTransferEffect.abi.idl"
#include "effects\generated\LuminancetoAlphaEffect.abi.idl"
#include "effects\generated\MorphologyEffect.abi.idl"
#include "effects\generated\OpacityMetadataEffect.abi.idl"
#include "effects\generated\PointDiffuseEffect.abi.idl"
#include "effects\generated\PointSpecularEffect.abi.idl"
#include "effects\generated\PremultiplyEffect.abi.idl"
#include "effects\generated\SaturationEffect.abi.idl"
#include "effects\generated\ScaleEffect.abi.idl"
#include "effects\generated\ShadowEffect.abi.idl"
#include "effects\generated\SpotDiffuseEffect.abi.idl"
#include "effects\generated\SpotSpecularEffect.abi.idl"
#include "effects\generated\TableTransferEffect.abi.idl"
#include "effects\generated\TileEffect.abi.idl"
#include "effects\generated\Transform2DEffect.abi.idl"
#include "effects\generated\Transform3DEffect.abi.idl"
#include "effects\generated\TurbulenceEffect.abi.idl"
#include "effects\generated\UnPremultiplyEffect.abi.idl"
