// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use these files except in compliance with the License. You may obtain
// a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

import "inspectable.idl";
import "Windows.Foundation.idl";
import "WinRTNumerics.idl";
#include "version.h"

namespace Microsoft.Graphics.Canvas
{
    //
    // ICanvasGeometry
    //
    [version(VERSION), uuid(A0D3D5DC-A2BD-4E5A-AA75-C13B8FF238C2)]
    interface ICanvasGeometry : IInspectable
        requires Windows.Foundation.IClosable
    {
    }
}
