import "inspectable.idl";
import "Windows.Foundation.idl";
import "Windows.UI.idl";
import "WinRTMath.idl";

#include "version.h"

namespace Microsoft.Graphics.Canvas
{
    [version(VERSION)]
    typedef enum CanvasDebugLevel
    {
        None = (int)0,
        Error = (int)1,
        Warning = (int)2,
        Information = (int)3
    } CanvasDebugLevel;

    [version(VERSION)]
    typedef struct CanvasEllipse
    {
        Windows.Foundation.Point Point;
        FLOAT RadiusX;
        FLOAT RadiusY;
    } CanvasEllipse;

    [version(VERSION)]
    typedef struct CanvasRoundedRectangle
    {
        Windows.Foundation.Rect Rect;
        FLOAT RadiusX;
        FLOAT RadiusY;
    } CanvasRoundedRectangle;

}
