// Copyright (c) Microsoft Corporation.  All rights reserved

import "inspectable.idl";
import "Windows.Foundation.idl";
import "WinRTMath.idl";
import "d2dwinrt.idl";
#include "version.h"

namespace Microsoft.Graphics.Canvas
{
    //
    // ICanvasGeometry
    //
    [version(VERSION), uuid(A0D3D5DC-A2BD-4E5A-AA75-C13B8FF238C2)]
    interface ICanvasGeometry : IInspectable
        requires Windows.Foundation.IClosable
    {
    }
}