import "inspectable.idl";
import "Windows.Foundation.idl";
import "DirectX.codegen.idl";

#include "version.h"

namespace Microsoft.DirectX
{

    //
    // This is a placeholder that demonstrates that we are able to build IDL
    // files. 
    //

    //
    // IDxResource
    //
    [uuid(300A4B09-5732-4472-BC78-987270FCBE49), version(VERSION)]
    interface IDxResource : IInspectable
        requires Windows.Foundation.IClosable
    {
    }
}
