// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Licensed under the MIT License. See LICENSE.txt in the project root for license information.

namespace Microsoft.Graphics.Canvas.Geometry
{
    runtimeclass CanvasCachedGeometry;

    [version(VERSION), uuid(BA6CB114-E1A1-448D-AB7C-8D2B92674119), exclusiveto(CanvasCachedGeometry)]
    interface ICanvasCachedGeometry : IInspectable
        requires Windows.Foundation.IClosable
    {
        [propget] HRESULT Device([out, retval] Microsoft.Graphics.Canvas.CanvasDevice** value);
    }

    [version(VERSION), uuid(80BA1060-A9D7-41BA-9372-EC3FC1744E5D), exclusiveto(CanvasCachedGeometry)]
    interface ICanvasCachedGeometryStatics : IInspectable
    {
        [overload("CreateFill")]
        HRESULT CreateFill(
            [in] CanvasGeometry* geometry,
            [out, retval] CanvasCachedGeometry** cachedGeometry);

        [overload("CreateFill"), default_overload]
        HRESULT CreateFillWithFlatteningTolerance(
            [in] CanvasGeometry* geometry,
            [in] float flatteningTolerance,
            [out, retval] CanvasCachedGeometry** cachedGeometry);

        [overload("CreateStroke")]
        HRESULT CreateStroke(
            [in] CanvasGeometry* geometry,
            [in] float strokeWidth,
            [out, retval] CanvasCachedGeometry** cachedGeometry);

        [overload("CreateStroke")]
        HRESULT CreateStrokeWithStrokeStyle(
            [in] CanvasGeometry* geometry,
            [in] float strokeWidth,
            [in] CanvasStrokeStyle* strokeStyle,
            [out, retval] CanvasCachedGeometry** cachedGeometry);

        [overload("CreateStroke"), default_overload]
        HRESULT CreateStrokeWithStrokeStyleAndFlatteningTolerance(
            [in] CanvasGeometry* geometry,
            [in] float strokeWidth,
            [in] CanvasStrokeStyle* strokeStyle,
            [in] float flatteningTolerance,
            [out, retval] CanvasCachedGeometry** cachedGeometry);
    }

    [STANDARD_ATTRIBUTES, static(ICanvasCachedGeometryStatics, VERSION)]
    runtimeclass CanvasCachedGeometry
    {
        [default] interface ICanvasCachedGeometry;
    }
}
