// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Licensed under the MIT License. See LICENSE.txt in the project root for license information.

//
// Types that are bound to Direct3D 11.
//

#define IDIRECT3DDEVICE Windows.Graphics.DirectX.Direct3D11.IDirect3DDevice
#define IDIRECT3DSURFACE Windows.Graphics.DirectX.Direct3D11.IDirect3DSurface
