// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Licensed under the MIT License. See LICENSE.txt in the project root for license information.

//
// Common / fundamental DirectX types.  These types are expected to remain
// common between Direct3D 11 and Direct3D 12.
//

#define DIRECTX_PIXEL_FORMAT Windows.Graphics.DirectX.DirectXPixelFormat

// Windows headers don't use enum classes, while headers built by Win2D do.  The
// PIXEL_FORMAT macro allows us to pick at compile type which type of enum we're
// consuming.
cpp_quote("#define PIXEL_FORMAT(x) ::ABI::Windows::Graphics::DirectX::DirectXPixelFormat_##x")
