// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use these files except in compliance with the License. You may obtain
// a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

namespace Microsoft.Graphics.Canvas.Effects
{
    [version(VERSION), uuid(3A339957-A95E-490E-A1BF-2CBF4806C378)]
    interface IEffect : IInspectable
		requires IEffectInput
    {
        [propget]
        HRESULT EffectId([out, retval] GUID* effectId);
        
        [propget]
        HRESULT Inputs([out, retval] Windows.Foundation.Collections.IVector<IEffectInput*>** inputs);
        
        [propget]
        HRESULT Properties([out, retval] Windows.Foundation.Collections.IVector<Windows.Foundation.IPropertyValue*>** effectProperties);
    }
}