// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Licensed under the MIT License. See LICENSE.txt in the project root for license information.

#pragma once

#include "Utilities.h"

//
// RAII type for managing COM arrays.  These are arrays that are passed to/from
// WinRT interfaces.  The memory backing them must be managed using
// CoTaskMemAlloc and CoTaskMemFree.
//
// There are two main scenarios for using this:
//
// 1. Retrieving an array from a WinRT API such as IPropertyValue.
//
//    ComArray<float> array;
//    ThrowIfFailed(propertyValue->GetSingleArray(array.GetAddressOfSize(), array.GetAddressOfData()));
//    if (array.GetSize() != 16)
//        ThowHR(E_BOUNDS);
//    *output = *(Numerics::Matrix4x4*)array.GetData();
//
//
// 2. Returning an array from a WinRT API:
//
//    ComArray<CanvasGradientStop> array;
//    // populate the array
//    array.Detach(valueCount, valueElements);
// 
//
// The array can be populated using the begin() iterator.  However, the
// CopyToComArray and TransformToComArray helpers capture common usage:
//
// std::vector<float> sourceFloats;
// ComArray<float> array(sourceFloats.begin(), sourceFloats.end());
//
// std::vector<int> sourceInts;
// ComArray<double> array = TransformToComArray<double>(sourceInts.begin(), sourceInts.end(), 
//     [](int v) { return static_cast<double>(v); });
//
//
// For testing purposes, ComArray is templated on a base class.  This
// CoTaskMemFree/CoTaskMemAlloc to be replaced with test doubles.
//
struct EmptyComArrayBase {};

template<typename T, typename Base=EmptyComArrayBase>
class ComArray : public Base
{
    T* m_data;
    uint32_t m_size;

public:
    static_assert(std::is_pod<T>::value, "T must be plain-old-data");

    ComArray(ComArray const&) = delete;
    ComArray& operator=(ComArray const&) = delete;

    ComArray()
        : m_data(nullptr)
        , m_size(0)
    {
    }

    ComArray(size_t size)
        : m_data(static_cast<T*>(CoTaskMemAlloc(size * sizeof(T))))
        , m_size(static_cast<uint32_t>(size))
    {
        assert(size <= UINT_MAX);
        if (!m_data)
            ThrowHR(E_OUTOFMEMORY);
    }

    template<typename ITERATOR>
    ComArray(ITERATOR first, ITERATOR last)
        : ComArray(std::distance(first, last))
    {
        std::copy(first, last, begin(*this));
    }

    ComArray(ComArray&& other)
        : m_data(nullptr)
        , m_size(0)
    {
        *this = std::move(other);
    }

    ComArray& operator=(ComArray&& other)
    {
        std::swap(m_data, other.m_data);
        std::swap(m_size, other.m_size);
        return *this;
    }

    ~ComArray()
    {
        Release();
    }

    uint32_t GetSize() const
    {
        return m_size;
    }

    T* GetData()
    {
        return m_data;
    }

    T const* GetData() const
    {
        return m_data;
    }

    T& operator[](uint32_t index)
    {
        assert(index < m_size);
        return m_data[index];
    }

    uint32_t* GetAddressOfSize()
    {
        Release();
        return &m_size;
    }

    T** GetAddressOfData()
    {
        Release();
        return &m_data;
    }

    void Detach(uint32_t* size, T** data)
    {
        *size = m_size;
        *data = m_data;
        
        m_size = 0;
        m_data = nullptr;
    }

private:
    void Release()
    {
        CoTaskMemFree(m_data);
        m_data = nullptr;
        m_size = 0;
    }
};

template<typename T, typename Base>
inline stdext::checked_array_iterator<T const*> begin(ComArray<T, Base> const& a)
{
    return stdext::checked_array_iterator<T const*>(a.GetData(), a.GetSize());
}

template<typename T, typename Base>
inline stdext::checked_array_iterator<T*> begin(ComArray<T, Base>& a)
{
    return stdext::checked_array_iterator<T*>(a.GetData(), a.GetSize());
}

template<typename T, typename Base>
inline stdext::checked_array_iterator<T const*> end(ComArray<T, Base> const& a)
{
    return stdext::checked_array_iterator<T const*>(a.GetData(), a.GetSize(), a.GetSize());
}

template<typename T, typename Base>
inline stdext::checked_array_iterator<T*> end(ComArray<T, Base>& a)
{
    return stdext::checked_array_iterator<T*>(a.GetData(), a.GetSize(), a.GetSize());
}

//
// Creates a new array where the values are generated by passing each element
// from the source range through func.
//
template<typename T, typename ITERATOR, typename FN, typename Base=EmptyComArrayBase>
inline ComArray<T, Base> TransformToComArray(ITERATOR first, ITERATOR last, FN func)
{
    auto size = std::distance(first, last);

    ComArray<T, Base> array(size);
    std::transform(first, last, begin(array), func);

    return array;
}
