// Copyright (c) Microsoft Corporation.  All rights reserved

import "inspectable.idl";
import "Windows.Foundation.idl";

#include "../../winrt/lib/version.h"


namespace Microsoft.Graphics.Canvas.Math
{
    [version(VERSION)]
    typedef struct Vector2
    {
        FLOAT X;
        FLOAT Y;
    } Vector2;


    [version(VERSION)]
    typedef struct Vector3
    {
        FLOAT X;
        FLOAT Y;
        FLOAT Z;
    } Vector3;


    [version(VERSION)]
    typedef struct Vector4
    {
        FLOAT X;
        FLOAT Y;
        FLOAT Z;
        FLOAT W;
    } Vector4;


    [version(VERSION)]
    typedef struct Matrix3x2
    {
        FLOAT M11, M12;
        FLOAT M21, M22;
        FLOAT M31, M32;
    } Matrix3x2;


    [version(VERSION)]
    typedef struct Matrix4x4
    {
        FLOAT M11, M12, M13, M14;
        FLOAT M21, M22, M23, M24;
        FLOAT M31, M32, M33, M34;
        FLOAT M41, M42, M43, M44;
    } Matrix4x4;


    [version(VERSION)]
    typedef struct Plane
    {
        Vector3 Normal;
        FLOAT D;
    } Plane;


    [version(VERSION)]
    typedef struct Quaternion
    {
        FLOAT X;
        FLOAT Y;
        FLOAT Z;
        FLOAT W;
    } Quaternion;
}
