// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Licensed under the MIT License. See LICENSE.txt in the project root for license information.

namespace Microsoft.Graphics.Canvas
{
    //
    // ICanvasImage
    //
    runtimeclass CanvasDrawingSession;

    [version(VERSION), uuid(794966D3-6A64-47E9-8DA8-B46AAA24D53B)]
    interface ICanvasImage : IInspectable
        requires IGRAPHICSEFFECTSOURCE, Windows.Foundation.IClosable
    {
        // The returned bounds reflect the DPI and UnitMode of the drawing session.
        [overload("GetBounds")]
        HRESULT GetBounds(
            [in] CanvasDrawingSession* drawingSession,
            [out, retval] Windows.Foundation.Rect* bounds);

        [overload("GetBounds")]
        HRESULT GetBoundsWithTransform(
            [in] CanvasDrawingSession* drawingSession,
            [in] NUMERICS.Matrix3x2 transform,
            [out, retval] Windows.Foundation.Rect* bounds);
    }
}
