@echo off

::
:: This generates an "update.cmd" script in the samples repo
:: that calls exportsample with the directory to the samples repo
:: filled in for you.
::

IF NOT EXIST "%1" (
    goto usage
)

set file=%1\update.cmd

echo @echo off > %file%
echo ::This file was generated by %~0 >> %file%
echo pushd %~dp0 >> %file%
echo call exportsample.cmd %1 %%* >> %file%
echo popd >> %file%

echo Wrote %file%

goto :EOF

:usage

echo Usage: %0 [samplesdir]
echo.
echo Creates "update.cmd" in samplesdir that will update the samples
echo from this repo.
